### PR TITLE
✨ Add genomic file target api builder

### LINKED ISSUE #189: Develop a target API builder for genomic file
Develop and test a target API builder for genomic file. Consider the following steps:

- [x] Add a new target API builder to the ingest plugin
- [x] Test ingest
- [x] Update the integration test

### PR DESCRIPTION
**Pull request by liberaliscomputing**
This PR:

- adds genomic file target API builder;
- updates integration test accordingly; and
- adds omitted identifier to sequencing center target API builder

It closes #189.

### CODE REVIEW

**Comment by liberaliscomputing** [comment]
The above CI tests look weird. In fact, the results from Jenkins and CircleCI conflict: Circle's result is same as local integration testing which has got passed.

**Comment by znatty22** [comment]
Ok @liberaliscomputing looking into it now

**Comment by znatty22** [comment]
Ok @liberaliscomputing looks like tests are passing. 

I think what _might_ have happened is the integration tests started during build 1, deployed a fresh temp integration test server, started loading, then exited due to an error - before getting to the part in the integration_test.sh script where its supposed to delete the temp integration test server. Then in subsequent builds, the integration_test.sh script sees a server running and doesn't run a new one, but there was probably old data in there causing the count tests to fail. I manually deleted the integration test server on Jenkins so that the integration_script.sh. 

I might update this script so that it's more resilient to this sort of thing.

**Comment by liberaliscomputing** [comment]
> Ok @liberaliscomputing looks like tests are passing.
> 
> I think what _might_ have happened is the integration tests started during build 1, deployed a fresh temp integration test server, started loading, then exited due to an error - before getting to the part in the integration_test.sh script where its supposed to delete the temp integration test server. Then in subsequent builds, the integration_test.sh script sees a server running and doesn't run a new one, but there was probably old data in there causing the count tests to fail. I manually deleted the integration test server on Jenkins so that the integration_script.sh.
> 
> I might update this script so that it's more resilient to this sort of thing.

@znatty22 , ah that makes sense totally. So, it failed because 4 != 2 from Organizations and the additional two were lingering from the previous build! Yeah, I remember I force-pushed a minor tweak during the first test was running. Thanks for digging into it!

**Review by fiendish — APPROVED** [review]

**Review by fiendish — APPROVED** [review]

**Pull request merged**
